clc;
close all;
clearvars;
MOTION_BLOCK_SIZE = 13;
DETAIL_THRESHOLD  = 80;
MOTION_THRESHOLD  = 200;
orig_frame_0 = imread( "./frame_0.png" );
orig_frame_1 = imread( "./frame_1.png" );
frame_0 = rgb2gray( orig_frame_0 );
frame_0 = imresize( frame_0, ceil( size( frame_0 ) ./ MOTION_BLOCK_SIZE ) .* MOTION_BLOCK_SIZE );
orig_frame_0 = imresize( orig_frame_0, size( frame_0 ) );
frame_1 = rgb2gray( orig_frame_1 );
frame_1 = imresize( frame_1, ceil( size( frame_1 ) ./ MOTION_BLOCK_SIZE ) .* MOTION_BLOCK_SIZE );
orig_frame_1 = imresize( orig_frame_1, size( frame_1 ) );
det_img = multiscaleMorphGrad( frame_0, [3, 5, 7] );
det_blocks = findDetailedBlocks( det_img, MOTION_BLOCK_SIZE, DETAIL_THRESHOLD );
[a, b, c] = findMotionVectors( frame_0, frame_1, det_blocks, MOTION_THRESHOLD );
imshow( placeBoxes( orig_frame_0, c, [255,0,0] ) );
